[tools]
"aqua:casey/just" = "1.46.0"
"aqua:cli/cli" = "2.87.3"
"aqua:jqlang/jq" = "1.7.1"
"aqua:mikefarah/yq" = "4.52.4"
"go" = "1.26.0"

[hooks]
postinstall = [
  "mkdir -p {{config_root}}/.cache",
]
