---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Deprecate App

on:
  workflow_dispatch:
    inputs:
      app:
        type: string
        description: App Name
        required: true
      reason:
        type: string
        description: Deprecation Reason
        required: true
      release:
        type: boolean
        description: Create Release
        default: true

permissions:
  contents: read

jobs:
  plan:
    name: Plan (${{ inputs.app }})
    runs-on: ubuntu-latest
    outputs:
      pull-number: ${{ steps.pr.outputs.pull-request-number }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Generate Token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ secrets.LAB_ASSISTANT_APP_ID }}
          private-key: ${{ secrets.LAB_ASSISTANT_APP_KEY }}

      - name: Delete App Directory
        env:
          APP: ${{ inputs.app }}
        run: |-
          rm -rf ./apps/${APP}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        id: pr
        with:
          body: |
            **Reason**: ${{ inputs.reason }}
          branch: deprecate/${{ inputs.app }}
          commit-message: "release(${{ inputs.app }})!: deprecate app image"
          sign-commits: true
          signoff: true
          title: "release(${{ inputs.app }})!: deprecate app image"
          token: ${{ steps.app-token.outputs.token }}

  merge:
    if: ${{ inputs.release }}
    name: Merge (${{ inputs.app }})
    needs:
      - plan
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ secrets.LAB_ASSISTANT_APP_ID }}
          private-key: ${{ secrets.LAB_ASSISTANT_APP_KEY }}

      - name: Merge Pull Request
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |-
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ needs.plan.outputs.pull-number }},
              merge_method: 'squash',
            });

  announce:
    if: ${{ inputs.release }}
    name: Announce (${{ inputs.app }})
    needs:
      - merge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Generate Token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ secrets.LAB_ASSISTANT_APP_ID }}
          private-key: ${{ secrets.LAB_ASSISTANT_APP_KEY }}

      - name: Get Release Tag
        uses: ./.github/actions/release-tag
        id: release
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Create Release
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
        with:
          body: |
            > [!WARNING]
            > An app has been deprecated and will no longer receive updates.
            > After **6 months** from now, its image will be **removed** from our container registry.

            ## ğŸ“¦ App

            **Name**: ${{ inputs.app }}
            **Reason**: ${{ inputs.reason }}
          tag: ${{ steps.release.outputs.tag }}
          token: ${{ steps.app-token.outputs.token }}
