---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Renovate

on:
  push:
    branches:
      - main
    paths:
      - .renovate.json5
      - .renovate/**.json5
  workflow_dispatch:

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ secrets.LAB_ASSISTANT_APP_ID }}
          private-key: ${{ secrets.LAB_ASSISTANT_APP_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Run Renovate
        uses: codex-/return-dispatch@2277c7e64ca38a7350b95cfec2d6715ccebb7108 # v3.0.1
        id: dispatch
        with:
          token: ${{ steps.app-token.outputs.token }}
          owner: ${{ github.repository_owner }}
          repo: admin
          ref: main
          workflow: schedule-renovate.yaml
          workflow_inputs: |-
            { "autodiscoverFilter": "${{ github.event.repository.name }}" }

      - name: Await Renovate Completion
        uses: Codex-/await-remote-run@a56c556e6434d2d7ec9438dc656143b39532324e # v1.13.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          owner: ${{ github.repository_owner }}
          repo: admin
          run_id: ${{ steps.dispatch.outputs.run_id }}

      - name: Renovate Output
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |-
          gh run view --repo ${{ github.repository_owner }}/admin --log ${{ steps.dispatch.outputs.run_id }}
