---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Vulnerability Scan

on:
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  apps:
    name: Get App Inventory
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.inventory.outputs.apps }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Get App Inventory
        uses: ./.github/actions/app-inventory
        id: inventory

  grype:
    name: Setup Grype
    runs-on: ubuntu-latest
    steps:
      - name: Create Cache Key
        id: cache
        run: echo "key=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Restore Database
        id: database-restore
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          key: grype-db-${{ steps.cache.outputs.key }}
          path: ~/.cache/grype/db

      - if: ${{ always() && steps.database-restore.outputs.cache-hit != 'true' }}
        name: Install Grype
        uses: anchore/scan-action/download-grype@2c901ab7378897c01b8efaa2d0c9bf519cc64b9e # v6.2.0
        id: grype

      - if: ${{ always() && steps.database-restore.outputs.cache-hit != 'true' }}
        name: Update Database
        run: |
          ${{ steps.grype.outputs.cmd }} db update

      - if: ${{ always() && steps.database-restore.outputs.cache-hit != 'true' }}
        name: Cache Database
        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          key: grype-db-${{ steps.cache.outputs.key }}
          path: ~/.cache/grype/db

  vulnerability-scan:
    needs: ["apps", "grype"]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: ${{ fromJSON(needs.apps.outputs.apps) }}
      max-parallel: 4
      fail-fast: false
    permissions:
      security-events: write
      contents: read
    steps:
      - name: Retreive Cache Key
        id: cache
        run: echo "key=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Restore Database
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          key: grype-db-${{ steps.cache.outputs.key }}
          path: ~/.cache/grype/db

      - name: Scan
        uses: anchore/scan-action@2c901ab7378897c01b8efaa2d0c9bf519cc64b9e # v6.2.0
        id: scan
        with:
          fail-build: false
          image: ghcr.io/${{ github.repository_owner }}/${{ matrix.app }}:rolling
          severity-cutoff: high

      - name: Upload Report
        uses: github/codeql-action/upload-sarif@ff0a06e83cb2de871e5a09832bc6a81e7276941f # v3.28.18
        with:
          category: container:${{ matrix.app }}
          sarif_file: ${{ steps.scan.outputs.sarif }}
